### ISSUE TITLE
How to run this from within ArcGIS Pro?

### ISSUE THREAD

**Issue by thomsonr** [nicogis/PAMChatGPT#1]
does this require API key or login to to OpenAi (have both)

**Comment by nicogis** [comment]
Api key

Il giorno lun 1 mag 2023 alle 15:33 thomsonr ***@***.***> ha
scritto:

**Comment by GiancaGIS** [comment]
You should set your API Key in ArcGIS Pro settings named: **_ChatGPT AddIn Settings_**

**Comment by thomsonr** [comment]
> You should set your API Key in ArcGIS Pro settings named: **_ChatGPT AddIn Settings_**

Thanks, how do I start/run PAMChatgpt?

**Comment by GiancaGIS** [comment]
Available release 1.0
